### ISSUE TITLE
Can't find the include file when the v files are in sub folder of workspaceroot

### ISSUE THREAD

**Issue by heartacker** [TheOneKevin/icarusext#4]
![iverlog-can-not-find-include](https://user-images.githubusercontent.com/1876302/117977550-8639c800-b363-11eb-9e29-7828d808ecf8.gif)

**Comment by TheOneKevin** [comment]
There is a setting called "Iverilog: Run At File Location" and it should work if you enable it.
If that is not enough, I will push an update that forces Icarus to include the current directory during compilation as well.

**Comment by heartacker** [comment]
thank for your tips. and actually i can't seek those setting before
![image](https://user-images.githubusercontent.com/1876302/118054510-f888c780-b3b8-11eb-93fa-3cc3d78a06ee.png)

finally i found it in:
![image](https://user-images.githubusercontent.com/1876302/118054635-3128a100-b3b9-11eb-91f5-558a5c594912.png)

and, i think we could add a setting named  `forces to include the current directory` as an option for user, 😄

**Comment by heartacker** [comment]
actually,there is no effect when checked `Iverilog: Run At File Location`

![image](https://user-images.githubusercontent.com/1876302/118055394-9af57a80-b3ba-11eb-839e-a426f7b0ae12.png)

**Comment by TheOneKevin** [comment]
Ah sorry, this is not in the release version of the plugin 😅. I will update this tonight when I have time. Thank you for the suggestions!
